name       : libssh2
version    : 1.6.0
release    : 2
source     :
    - http://www.libssh2.org/download/libssh2-1.6.0.tar.gz : 5a202943a34a1d82a1c31f74094f2453c207bf9936093867f41414968c8e8215
license    : MIT
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
