name       : libssh2
version    : 1.8.0
release    : 5
source     :
    - https://www.libssh2.org/download/libssh2-1.8.0.tar.gz : 39f34e2f6835f4b992cafe8625073a88e5a28ba78f83e8099610a7b3af4676d4
license    : MIT
component  : system.base
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
emul32     : yes
builddeps  :
    - pkgconfig32(libssl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
