name       : libssh2
version    : 1.6.0
release    : 1
source     :
    - http://www.libssh2.org/download/libssh2-1.6.0.tar.gz : 5a202943a34a1d82a1c31f74094f2453c207bf9936093867f41414968c8e8215
license    : BSD
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
libsplit : no
patterns :
    - docs: [/usr/share/man]
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(zlib)
setup      : |
    %configure --mandir=/usr/share/man/man3/libssh2 --disable-static --disable-rpath --with-libz --with-openssl
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/share/man/man3/libssh2/man3/* $installdir/usr/share/man/man3/libssh2/
    rmdir $installdir/usr/share/man/man3/libssh2/man3
