name       : libssh2
version    : 1.11.0
release    : 11
source     :
    - https://github.com/libssh2/libssh2/releases/download/libssh2-1.11.0/libssh2-1.11.0.tar.xz : a488a22625296342ddae862de1d59633e6d446eff8417398e06674a49be3d7c2
license    : MIT
component  : system.base
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
emul32     : yes
builddeps  :
    - pkgconfig32(zlib)
    - pkgconfig32(libcrypto)
    # Temporary, can be removed after the openssl 3.1 rebuilds
    - openssl-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/static-no-tests.patch
    %patch -p1 < $pkgfiles/fix-cmake.patch

    ./buildconf
    %configure --disable-static --with-crypto=openssl --disable-docker-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
