name       : libssh2
version    : 1.9.0
release    : 9
source     :
    - git|https://github.com/libssh2/libssh2.git : 9b5407f91b7b88d3fb5fc63cbc950ac13d325f84
license    : MIT
component  : system.base
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
emul32     : yes
builddeps  :
    - openssl-11-32bit-devel
setup      : |
    ./buildconf
    %configure --disable-static --with-crypto=openssl
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
