name       : libssh2
version    : 1.8.0
release    : 6
source     :
    - https://github.com/libssh2/libssh2/archive/libssh2-1.8.0.tar.gz : 973f63f98141d68b4a1bc85791ee29411eeab12a6230ae1aca9c368550ccafae
license    : MIT
component  : system.base
summary    : libssh2 is a client-side C library implementing the SSH2 protocol
description: |
    libssh2 is a client-side C library implementing the SSH2 protocol
emul32     : yes
builddeps  :
    - pkgconfig32(libssl)
setup      : |
    ./buildconf
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
